task:
  name: Olympus
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 4.0
    clipObservations: 1000.0
    clipActions: 1000.0
    controlFrequencyInv: 4
    RLSetup:
      num_observations: 31
      num_actions: 12
      num_articulated_joints: 20
    control:
      stiffness: 5.0
      damping: 0.2
      torque_speed_coefficients:
      - -1.90985931929
      - 72
      max_torque: 24.8
    defaultJointAngles:
      LateralMotor_FL: 0.0
      LateralMotor_BR: 0.0
      LateralMotor_BL: 0.0
      LateralMotor_FR: 0.0
      FrontTransversalMotor_FR: 0.0
      FrontTransversalMotor_FL: 0.0
      FrontTransversalMotor_BR: 0.0
      FrontTransversalMotor_BL: 0.0
      BackTransversalMotor_FR: 0.0
      BackTransversalMotor_FL: 0.0
      BackTransversalMotor_BR: 0.0
      BackTransversalMotor_BL: 0.0
      FrontKnee_FR: 0.0
      FrontKnee_FL: 0.0
      FrontKnee_BR: 0.0
      FrontKnee_BL: 0.0
      BackKnee_FR: 0.0
      BackKnee_FL: 0.0
      BackKnee_BR: 0.0
      BackKnee_BL: 0.0
    jointLimits:
      lateralMotor:
      - -180
      - 20
      transversalMotor:
      - -60
      - 180
      maxTransversalMotorDiff: -10
      maxTransversalMotorSum: 220
      maxJointVelocity: 1500.0
    learn:
      rewards:
        total: 1
        r_orient: 2
        r_base_acc: 0
        r_action_clip: 0.01
        r_torque_clip: 1.0e-06
        r_collision: 0
        r_is_done: 100
        r_inside_threshold: 1
        r_orient_integral: 0
        r_joint_acc: 0
        r_velocity: 2.0e-05
        r_change_dir: 0.035
        r_regularize: 0.002
      cNumberOfLevels: 1
      cNextLevelThreshold: 5
      angleErrorThreshold: 2
      rOrientRewardTemp: 0.7
      episodeLength_s: 3
  sim:
    dt: 0.00208
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - 0.0
    add_ground_plane: false
    use_flatcache: true
    enable_scene_query_support: false
    disable_contact_processing: true
    enable_cameras: false
    default_physics_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      worker_thread_count: ${....num_threads}
      solver_type: 0
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 1
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: true
      max_depenetration_velocity: 100.0
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 163840
      gpu_found_lost_pairs_capacity: 4194304
      gpu_found_lost_aggregate_pairs_capacity: 33554432
      gpu_total_aggregate_pairs_capacity: 4194304
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 134217728
      gpu_temp_buffer_capacity: 33554432
      gpu_max_num_partitions: 8
    Olympus:
      override_usd_defaults: false
      enable_self_collisions: true
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 1
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 128
        - 64
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: false
    load_path: ''
    config:
      name: ${resolve_default:Olympus,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      env_name: rlgpu
      multi_gpu: ${....multi_gpu}
      ppo: true
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      e_clip: 0.2
      entropy_coef: 0.0
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      truncate_grads: true
      grad_norm: 10.0
      horizon_length: 60
      minibatch_size: 49152
      mini_epochs: 15
      critic_coef: 2
      clip_value: false
      clip_actions: true
      seq_len: 4
      bound_loss_type: bound
      bounds_loss_coef: 0.01
      max_epochs: ${resolve_default:3000,${....max_iterations}}
      save_best_after: 50
      score_to_win: 20000
      save_frequency: 50
      print_stats: true
task_name: ${task.name}
experiment: ''
RL_task: 3D
num_envs: ''
seed: 3605
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
multi_gpu: false
num_threads: 4
solver_type: 0
test: false
checkpoint: ''
headless: true
enable_livestream: true
stream_type: webRTC
mt_timeout: 30
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: omniisaacgymenvs
warp: false
